# Generated by Django 3.1.5 on 2021-04-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atracciones',
            fields=[
                ('id_atraccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('capacidad', models.SmallIntegerField()),
                ('fecha', models.DateTimeField(max_length=254)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=250)),
                ('reserva', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='promociones',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=200)),
                ('clave', models.CharField(max_length=254)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(max_length=254)),
                ('costo', models.DecimalField(decimal_places=10, max_digits=250)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diverty.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('fecha', models.DateTimeField()),
                ('atracciones_reservas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserva_atracciones', to='diverty.atracciones')),
            ],
        ),
        migrations.CreateModel(
            name='detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_ventas', models.DecimalField(decimal_places=10, max_digits=250)),
                ('cantidad', models.CharField(max_length=254)),
                ('total_pagar', models.DecimalField(decimal_places=10, max_digits=250)),
                ('detalles_id_atraccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diverty.atracciones')),
                ('detalles_id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diverty.ventas')),
            ],
        ),
        migrations.AddField(
            model_name='atracciones',
            name='promociones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diverty.promociones'),
        ),
    ]
